spring:
  application:
    name: dubbo-samples
dubbo:
  protocol:
    name: dubbo
    port: 7777
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    group: relesase
    version: "1.0.0"
    timeout: 30000
  consumer:
    version: "1.0.0"
    group: relesase
    timeout: 30000