httpClientService:
  connectionRequestTimeout: 500
  connectTimeout: 5000
  socketTimeout: 30000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 100
  header: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36" }
  requestSentRetryEnabled: false
  closeTask:
    name: httpClient2-close-task
    idleTime: 4000
    initialDelay: 4000
    delay: 4000
spring:
  application:
    name: relesase-manager
  shell:
    command:
      script:
        enabled: false
      stacktrace:
        enabled: false

